---
- name: "create local path"
  file:
    path: '{{ local_path }}'
    state: directory
    recurse: yes
    mode: 0775
  tags: init

- name: generate composer file
  template:
    src: docker-compose.yml.j2
    dest: '{{ local_path }}/{{ project }}.yml'
    mode: preserve
  tags: init

- name: generate control files
  template:
    src: control.j2
    dest: '{{ local_path }}/{{ project }}'
    mode: '+x'
  tags: init
