---
- name: 'caddy : service init'
  include_tasks: service_common.yml
  vars:
    - service_name: caddy
    - service_image_dir: '{{ build_path }}/images/caddy'
    - service_dirs:
        - certs
        - private
        - pki
    - service_gen_certs:
        - "pki.{{ sonet_general['domain'] }}"
        - "gitlab.{{ sonet_general['domain'] }}"
        - "ldapadmin.{{ sonet_general['domain'] }}"
        - "mail.{{ sonet_general['domain'] }}"
        - "mattermost.{{ sonet_general['domain'] }}"
        - "redmine.{{ sonet_general['domain'] }}"
        - "registry.{{ sonet_general['domain'] }}"
        - "storage.{{ sonet_general['domain'] }}"
        - "excalidraw.{{ sonet_general['domain'] }}"
        - "nextcloud.{{ sonet_general['domain'] }}"
        - "onlyoffice.{{ sonet_general['domain'] }}"
        - "drawio.{{ sonet_general['domain'] }}"
        - "portainer.{{ sonet_general['domain'] }}"
        - "adminer.{{ sonet_general['domain'] }}"
        - "grafana.{{ sonet_general['domain'] }}"
    - service_copy_certs:
        - { src: "ca.crt", dest: "certs/ca.crt" }
        - { src: "ca.crt", dest: "pki/ca.crt" }
        - { src: "dh.pem", dest: "certs/dhparam.pem" }
        - { src: "issued/gitlab.{{ sonet_general['domain'] }}.crt", dest: "certs/gitlab.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/gitlab.{{ sonet_general['domain'] }}.key", dest: "private/gitlab.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/mattermost.{{ sonet_general['domain'] }}.crt", dest: "certs/mattermost.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/mattermost.{{ sonet_general['domain'] }}.key", dest: "private/mattermost.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/mail.{{ sonet_general['domain'] }}.crt", dest: "certs/mail.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/mail.{{ sonet_general['domain'] }}.key", dest: "private/mail.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/registry.{{ sonet_general['domain'] }}.crt", dest: "certs/registry.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/registry.{{ sonet_general['domain'] }}.key", dest: "private/registry.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/redmine.{{ sonet_general['domain'] }}.crt", dest: "certs/redmine.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/redmine.{{ sonet_general['domain'] }}.key", dest: "private/redmine.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/ldapadmin.{{ sonet_general['domain'] }}.crt", dest: "certs/ldapadmin.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/ldapadmin.{{ sonet_general['domain'] }}.key", dest: "private/ldapadmin.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/pki.{{ sonet_general['domain'] }}.crt", dest: "certs/pki.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/pki.{{ sonet_general['domain'] }}.key", dest: "private/pki.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/excalidraw.{{ sonet_general['domain'] }}.crt", dest: "certs/excalidraw.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/excalidraw.{{ sonet_general['domain'] }}.key", dest: "private/excalidraw.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/nextcloud.{{ sonet_general['domain'] }}.crt", dest: "certs/nextcloud.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/nextcloud.{{ sonet_general['domain'] }}.key", dest: "private/nextcloud.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/onlyoffice.{{ sonet_general['domain'] }}.crt", dest: "certs/onlyoffice.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/onlyoffice.{{ sonet_general['domain'] }}.key", dest: "private/onlyoffice.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/drawio.{{ sonet_general['domain'] }}.crt", dest: "certs/drawio.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/drawio.{{ sonet_general['domain'] }}.key", dest: "private/drawio.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/portainer.{{ sonet_general['domain'] }}.crt", dest: "certs/portainer.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/portainer.{{ sonet_general['domain'] }}.key", dest: "private/portainer.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/adminer.{{ sonet_general['domain'] }}.crt", dest: "certs/adminer.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/adminer.{{ sonet_general['domain'] }}.key", dest: "private/adminer.{{ sonet_general['domain'] }}.key" }
        - { src: "issued/grafana.{{ sonet_general['domain'] }}.crt", dest: "certs/grafana.{{ sonet_general['domain'] }}.crt" }
        - { src: "private/grafana.{{ sonet_general['domain'] }}.key", dest: "private/grafana.{{ sonet_general['domain'] }}.key" }
  tags: [init, build, push]
