---
- name: 'cadvisor : service init'
  include_tasks: service_common.yml
  vars:
    - service_name: cadvisor
    - service_image_dir: '{{ build_path }}/images/cadvisor'
  tags: [init, build, push]

- name: 'prometheus : service init'
  include_tasks: service_common.yml
  vars:
    - service_name: prometheus
    - service_image_dir: '{{ build_path }}/images/prometheus'
    - service_dirs:
        - service/prometheus
    - service_copy_files:
        - { src: "{{ playbook_dir }}/files/monitoring/prometheus/", dest: "{{ build_path }}/images/prometheus/service/prometheus/" }
  tags: [init, build, push]

- name: 'pushgateway : service init'
  include_tasks: service_common.yml
  vars:
    - service_name: pushgateway
    - service_image_dir: '{{ build_path }}/images/pushgateway'
  tags: [init, build, push]

- name: 'node-exporter : service init'
  include_tasks: service_common.yml
  vars:
    - service_name: node-exporter
    - service_image_dir: '{{ build_path }}/images/node-exporter'
  tags: [init, build, push]
