---
- name: 'redmine : service init'
  include_tasks: service_common.yml
  vars:
    - service_name: redmine
    - service_image_dir: '{{ local_path }}/images/redmine'
    - service_dirs:
        - service/redmine/plugins
        - service/redmine/themes
  tags: [init, build, push]

- name: 'redminedb : service init'
  include_tasks: service_common.yml
  vars:
    - service_name: redminedb
    - service_image_dir: '{{ local_path }}/images/redminedb'
  tags: [init, build, push]

- name: 'redmine : get plugins and themes'
  include_tasks: helper_get_url.yml
  loop: "{{ redmine['plugins_and_themes'] }}"
  when: redmine.plugins_and_themes is defined
  tags: init

- name: 'redmine : copy plugins'
  copy:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    mode: 0775
  loop:
    - { src: "{{ playbook_dir }}/redmine/plugins/", dest: "{{ local_path }}/images/redmine/service/redmine/plugins/" }
    - { src: "{{ playbook_dir }}/redmine/themes/", dest: "{{ local_path }}/images/redmine/service/redmine/themes/" }
  tags: init
